os: linux
dist: bionic
language: python

python: 3.8

install:
- pip install flake8 setuptools-scm twine
- pip install --editable .

script:
- pytest --verbose
# Check code style
- flake8 iam_units/*.py
# Test package build
- python3 setup.py bdist_wheel sdist && twine check dist/*
