name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install and test with pytest
      run: |
        pip install numpy pytest setuptools-scm
        pip install --editable .
        pytest --verbose

    - name: Upload test coverage to Codecov.io
      uses: codecov/codecov-action@v1.2.1
